SELECT e.FIRST_NAME, e.LAST_NAME, e.JOB_ID FROM EMPLOYEES e;

SELECT * FROM EMPLOYEES e ORDER BY e.JOB_ID DESC ; --ASC

SELECT e.LAST_NAME, e.SALARY FROM EMPLOYEES e WHERE e.SALARY NOT BETWEEN 5000 AND 12000;

SELECT e.LAST_NAME, e.DEPARTMENT_ID FROM EMPLOYEES e WHERE (e.DEPARTMENT_ID IN 20 OR e.DEPARTMENT_ID IN 50) ORDER BY e.LAST_NAME ASC;

SELECT e.LAST_NAME ,e.DEPARTMENT_ID FROM EMPLOYEES e WHERE e.SALARY NOT IN (2500, 3500 , 7000) AND e.JOB_ID NOT IN ('INSA_REP', 'ST_CLERK');

SELECT * FROM EMPLOYEES e WHERE e.HIRE_DATE BETWEEN '2014-01-01' AND '2014-12-31';

SELECT e.EMPLOYEE_ID, e.LAST_NAME FROM EMPLOYEES e WHERE e.LAST_NAME LIKE '%u%';

SELECT e.EMPLOYEE_ID, e.LAST_NAME FROM EMPLOYEES e WHERE e.LAST_NAME LIKE '___a%';

SELECT e.EMPLOYEE_ID, e.LAST_NAME FROM EMPLOYEES e WHERE e.LAST_NAME LIKE '%a%' OR E.LAST_NAME LIKE '%e%' ORDER BY e.LAST_NAME DESC;

SELECT e.EMPLOYEE_ID, e.LAST_NAME FROM EMPLOYEES e WHERE e.LAST_NAME LIKE '%a%' AND E.LAST_NAME LIKE '%e%' ORDER BY e.LAST_NAME DESC;

SELECT e.LAST_NAME, e.JOB_ID FROM EMPLOYEES e WHERE e.MANAGER_ID IS NULL;

SELECT DISTINCT e.DEPARTMENT_ID FROM EMPLOYEES e WHERE NOT (e.JOB_ID = 'ST_CLERK') AND e.DEPARTMENT_ID IS NOT NULL;

SELECT e.EMPLOYEE_ID, e.FIRST_NAME, e.JOB_ID, (e.COMMISSION_PCT * e.SALARY) as COMMISSION FROM EMPLOYEES e WHERE e.COMMISSION_PCT IS NOT NULL ;