
SELECT * FROM EMP e;

SELECT e.EMPNO, e.ENAME, e.job FROM EMP e; 

SELECT e.EMPNO, e.DEPTNO FROM EMP e;

SELECT DISTINCT e.EMPNO, e.DEPTNO FROM EMP e;

SELECT  * FROM EMP e ORDER BY e.DEPTNO DESC, e.ENAME ASC;

SELECT * FROM EMP e WHERE e.sal BETWEEN 2000 AND 3000;

SELECT * FROM EMP e WHERE e.ENAME LIKE '_L%';

SELECT * FROM EMP e WHERE e.ENAME LIKE '%AM%';

SELECT * FROM EMP e WHERE e.ENAME NOT LIKE '%AM%';

SELECT * FROM EMP e WHERE e.MGR IS not NULL;

SELECT sysdate AS now, sysdate-1 AS yesterday, sysdate+1 AS tomorrow,
	CURRENT_DATE AS curdate, CURRENT_TIMESTAMP AS curtime
FROM dual;

SELECT sysdate, ADD_MONTHS(sysdate, 3)
FROM dual;

SELECT e.EMPNO, e.ENAME, e.HIREDATE, TRUNC(MONTHS_BETWEEN(sysdate, e.HIREDATE))
FROM EMP e;

SELECT sysdate, NEXT_DAY(sysdate,'월요일'), LAST_DAY(sysdate)
FROM dual;
 	--자동 형변환
SELECT e.EMPNO, e.ENAME, e.EMPNO+'500'
FROM EMP e 
WHERE e.ENAME = 'SMITH';

SELECT TO_CHAR(sysdate,'YYYY/MM/DD, YY MON MONTH DY DAY HH:MI:SS HH12 HH24 AM PM')
FROM dual;

SELECT e.SAL, TO_CHAR(e.SAL, '$999,000')
FROM EMP e;

--empno 99**, ename N****
SELECT e.EMPNO, SUBSTR(e.EMPNO, 0, 2)||'**' AS "EMPNO Masked",
e.ENAME, SUBSTR(e.ENAME, 0, 1)||SUBSTR('********',0,LENGTH(e.ENAME)-1) AS "ENAME Masked"
FROM EMP e;

--평균 근무일 21, 하루 8시간으로 하루 급여(day_pay), 시급(time_pay) / 일급은 소수 셋자리 버림, 시급 두자리 반올림
-- EMPNO, ENAME, SAL, DAY_PAY, TIME_PAY
SELECT e.EMPNO, e.ENAME, e.SAL, TRUNC(e.SAL/21, 2) AS "DAY_PAY", ROUND((e.SAL/21)/8,1) AS "TIME_PAY"
FROM EMP e;

--입사일기준 3개월후 첫 월요일에 정직원, 정직원날짜(R_HOB) YYYY-MM-DD, 추가수당 없으면 N/A 출력
-- EMPNO, ENAME, HIERDARE, R_JOB, COMM
SELECT e.EMPNO, e.ENAME, TO_CHAR(e.HIREDATE,'YYYY-MM-DD') AS "HIREDATE",
TO_CHAR(NEXT_DAY((ADD_MONTHS(e.HIREDATE, 3)),'월요일'),'YYYY-MM-DD') AS "R_JOB", NVL(TO_CHAR(e.COMM), 'N/A') AS "COMM"
FROM EMP e;

--직속상관의 사원번호 X = 0000, 두번째자리 XXXX 5~8만
-- EMPNO, ENAME, MGR, CHG_MGR
SELECT e.EMPNO, e.ENAME, e.MGR, 
CASE WHEN e.MGR IS NULL THEN '0000'
WHEN e.MGR LIKE '75%' THEN '5555'
WHEN e.MGR LIKE '76%' THEN '6666'
WHEN e.MGR LIKE '77%' THEN '7777'
WHEN e.MGR LIKE '78%' THEN '8888'
ELSE TO_CHAR(e.MGR) END AS "CHG_MGR"
FROM EMP e;

SELECT e.EMPNO, e.ENAME, e.MGR, 
DECODE(SUBSTR(TO_CHAR(e.MGR),1,2),
NULL, '0000',
'75', '5555',
'76', '6666',
'77', '7777',
'78', '8888',
TO_CHAR(e.MGR))
FROM EMP e;

SELECT sum(e.sal) FROM EMP e;
SELECT sum(e.sal), sum(DISTINCT e.sal) FROM EMP e;
SELECT count(e.EMPNO) FROM EMP e ;
SELECT MAX(e.SAL), MIN(e.SAL) FROM EMP e ;
SELECT MAX(e.SAL) FROM EMP e WHERE e.DEPTNO = 10;
SELECT MAX(e.HIREDATE), MIN(e.HIREDATE) FROM EMP e WHERE e.DEPTNO = 20;
SELECT AVG(e.SAL) FROM EMP e WHERE e.DEPTNO = 30;