
SELECT * FROM EMP e;

SELECT e.EMPNO, e.ENAME, e.job FROM EMP e; 

SELECT e.EMPNO, e.DEPTNO FROM EMP e;

SELECT DISTINCT e.EMPNO, e.DEPTNO FROM EMP e;

SELECT  * FROM EMP e ORDER BY e.DEPTNO DESC, e.ENAME ASC;

SELECT * FROM EMP e WHERE e.sal BETWEEN 2000 AND 3000;

SELECT * FROM EMP e WHERE e.ENAME LIKE '_L%';

SELECT * FROM EMP e WHERE e.ENAME LIKE '%AM%';

SELECT * FROM EMP e WHERE e.ENAME NOT LIKE '%AM%';

SELECT * FROM EMP e WHERE e.MGR IS not NULL;